# demo_setup.yml
# How to execute: ansible-playbook demo_setup.yml
# Ref: https://docs.ansible.com/ansible/2.6/scenario_guides/guide_aws.html

- hosts: localhost
  connection: local
  gather_facts: False
  #Best pratice: Insert this into a vars_file
  vars:
    keypair: ubuntu18.04
    instance_type: t2.micro
    image: ami-7c491f05
    region: eu-west-1
    access_key: <your aws_access_key>
    secret_key: <your aws_secret_key>

  tasks:

    - name: Provision a set of instances
      ec2:
         key_name: "{{ keypair }}"
         group: default
         instance_type: "{{ instance_type }}"
         image: "{{ image }}"
         wait: true
         exact_count: 1
         count_tag:
            Name: Demo
         instance_tags:
            Name: Demo
         region: "{{ region }}"
         aws_access_key: "{{ access_key }}"
         aws_secret_key: "{{ secret_key }}"
      register: ec2
    
    - name: Add all instance public IPs to host group
      add_host: hostname={{ item.public_ip }} groups=ec2hosts
      loop: "{{ ec2.instances }}"
 
    - name: Print all ec2 variables
      debug: var=ec2
